{
    'minecraft:air': 0,
    'minecraft:spruce_door[hinge=right, half=upper, powered=false, facing=north, open=false]': 1,
    'minecraft:lantern[waterlogged=false, hanging=true]': 2,
    'minecraft:spruce_fence[east=false, waterlogged=false, south=false, north=true, west=false]': 3,
    'minecraft:stripped_spruce_wood[axis=y]': 4,
    'minecraft:smooth_stone_slab[waterlogged=false, type=top]': 5,
    'minecraft:spruce_stairs[half=bottom, waterlogged=false, shape=straight, facing=east]': 6,
    'minecraft:glass_pane[east=false, waterlogged=false, south=true, north=true, west=false]': 7,
    'minecraft:spruce_stairs[half=bottom, waterlogged=false, shape=straight, facing=west]': 8,
    'minecraft:snow[layers=1]': 9,
    'minecraft:spruce_fence[east=true, waterlogged=false, south=false, north=false, west=true]': 10,
    'minecraft:spruce_door[hinge=left, half=lower, powered=false, facing=south, open=false]': 11,
    'minecraft:spruce_door[hinge=left, half=upper, powered=false, facing=south, open=false]': 12,
    'minecraft:spruce_slab[waterlogged=false, type=bottom]': 13,
    'minecraft:spruce_fence[east=true, waterlogged=false, south=true, north=false, west=true]': 14,
    'minecraft:jigsaw[orientation=north_up]': 15,
    'minecraft:grass_block[snowy=true]': 16,
    'minecraft:smooth_stone': 17,
    'minecraft:stripped_spruce_wood[axis=x]': 18,
    'minecraft:spruce_slab[waterlogged=false, type=double]': 19,
    'minecraft:spruce_fence[east=false, waterlogged=false, south=true, north=true, west=false]': 20,
    'minecraft:cobblestone_wall[east=none, waterlogged=false, south=none, north=none, west=low, up=true]': 21,
    'minecraft:spruce_planks': 22,
    'minecraft:smoker[lit=false, facing=north]': 23,
    'minecraft:spruce_fence[east=true, waterlogged=false, south=false, north=true, west=true]': 24,
    'minecraft:spruce_door[hinge=right, half=lower, powered=false, facing=north, open=false]': 25,
    'minecraft:spruce_fence[east=false, waterlogged=false, south=false, north=true, west=true]': 26,
    'minecraft:cobblestone': 27,
    'minecraft:cobblestone_wall[east=tall, waterlogged=false, south=tall, north=none, west=none, up=true]': 28,
    'minecraft:jigsaw[orientation=up_north]': 29,
    'minecraft:grass_block[snowy=false]': 30,
    'minecraft:cobblestone_wall[east=none, waterlogged=false, south=none, north=none, west=none, up=true]': 31,
    'minecraft:spruce_slab[waterlogged=false, type=top]': 32,
    'minecraft:spruce_fence[east=true, waterlogged=false, south=false, north=true, west=false]': 33,
}
